### ISSUE TITLE
default normalization in postPredSPD.R

### ISSUE THREAD

**Issue by rdinapoli** [ercrema/nimbleCarbon#3]
I've been running some model diagnostics and was confused why the output of `postPredSPD` looked different than my observed SPD. I think the routine in this function assumes the user wants the observed and simulated SPDs to have normalized dates. Specifically:
https://github.com/ercrema/nimbleCarbon/blob/5ff61190845d8fc00f0630a8f3313539b8050846/R/postPredSPD.R#L67
and
https://github.com/ercrema/nimbleCarbon/blob/5ff61190845d8fc00f0630a8f3313539b8050846/R/postPredSPD.R#L114
What do you think about making this an argument of the function?

**Comment by ercrema** [comment]
Sounds good - will add that as an argument

**Comment by rdinapoli** [comment]
Excellent. Thanks!

**Comment by ercrema** [comment]
Added feature in commit 10ce39c7a453b040bcbef6623ca3e886a8d6dc46
